//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPrint.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpEntities : DbContext
    {
        public erpEntities()
            : base("name=erpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<base_privilege_entity> base_privilege_entity { get; set; }
        public DbSet<base_user> base_user { get; set; }
        public DbSet<wh_split_package> wh_split_package { get; set; }
        public DbSet<wh_transfer_details> wh_transfer_details { get; set; }
    }
}
