//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPrint.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_split_package
    {
        public long id { get; set; }
        public Nullable<long> productId { get; set; }
        public string productName { get; set; }
        public string srcPackageNumber { get; set; }
        public string destPackageNumber { get; set; }
        public Nullable<long> transferId { get; set; }
        public string transferNumber { get; set; }
        public Nullable<long> locationId { get; set; }
        public string locationName { get; set; }
        public Nullable<double> quantity { get; set; }
        public string supplier { get; set; }
        public string project { get; set; }
        public Nullable<long> manId { get; set; }
        public string companyCode { get; set; }
        public string internalReference { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
