//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPrint.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_transfer_details
    {
        public long id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> transfer_id { get; set; }
        public Nullable<int> transfer_item_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_id { get; set; }
        public string man_pn { get; set; }
        public Nullable<double> done_quantity { get; set; }
        public Nullable<int> uom_id { get; set; }
        public string uom_name { get; set; }
        public Nullable<int> src_location_id { get; set; }
        public Nullable<int> dest_location_id { get; set; }
        public string dest_package_number { get; set; }
        public Nullable<int> man_id { get; set; }
        public Nullable<int> status { get; set; }
        public string trace_number { get; set; }
        public string src_package_number { get; set; }
    }
}
